name: cuda-check

on:
  push:
    branches:
      - master

jobs:
  cuda:
    runs-on: ubuntu:latest
    steps:
      - name: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: "12.1.0"
      - run: nvcc --version
